import java.util.*

plugins {
    `java-library`
    kotlin("jvm")
    kotlin("kapt")
}

kapt.javacOptions {
    option("-source", "16")
    option("-target", "1.8")
}

sourceSets {
    main {
        java.srcDirs("src/", layout.buildDirectory.dir("/generated/sources/annotationProcessor/java/main"))
    }
}

tasks {
    val generateLocales by registering {
        val outFile = projectDir.resolve("assets/locales")
        outputs.file(outFile)
        val bundles = projectDir.resolve("assets/bundles/").list()!!
                .filter { it != "bundle.properties" }
                .map { it.substring("bundle".length + 1, it.lastIndexOf('.')) }
                .sorted()
        inputs.property("bundles", bundles)
        doLast {
            outFile.writeText(bundles.joinToString("\n"))
        }
    }
    val generateBasePartNames by registering {
        val outFile = projectDir.resolve("assets/basepartnames")
        outputs.file(outFile)
        val baseParts = projectDir.resolve("assets/baseparts/").list()!!.sorted()
        inputs.property("baseParts", baseParts)
        doLast {
            outFile.writeText(baseParts.joinToString("\n"))
        }
    }
    val writeVersion by registering(WriteProperties::class) {
        destinationFile = projectDir.resolve("assets/version.properties")
        comment = "Autogenerated file. Do not modify."
        property("type", properties.getOrDefault("versionType", "official"))
        property("modifier", properties.getOrDefault("versionModifier", "release"))
        property("number", '7')
        property("build", properties.getOrDefault("buildversion", "custom build"))
    }
    val preGen by registering {
        dependsOn(generateLocales, generateBasePartNames, writeVersion)
    }
    processResources.configure { dependsOn(preGen) }

    val allAssets by registering {
        dependsOn(preGen, ":tools:pack")
        outputs.dir("assets")
    }

    val assetsJar by registering(Jar::class) {
        from(allAssets) {
            exclude("config", "cache", "music", "sounds")
        }
    }
    val musicJar by registering(Jar::class) {
        archiveClassifier.set("music")
        from("assets") {
            include("music/*", "sounds/*")
        }
    }

    val copyChangelog by registering {
        val androidVersion = Properties().apply {
            file("assets/version.properties").inputStream().use(this::load)
        }.getProperty("androidBuildCode").toInt() - 2
        val inFile = file("../changelog")
        val outFile = file("../fastlane/metadata/android/en-US/changelogs/$androidVersion.txt")
        inputs.property("androidVersion", androidVersion)
        inputs.file(inFile)
        outputs.file(outFile)
        doLast {
            outFile.parentFile.mkdirs()
            outFile.writeText(buildString {
                appendLine("[This is a truncated changelog, see Github for full notes]")
                inFile.forEachLine {
                    if (it.endsWith("]") && !(it.endsWith("[Mobile]") || it.endsWith("[Android]"))) return@forEachLine
                    if (length + it.length + 1 < 460) return@forEachLine//maxLength
                    appendLine(it)
                }
            })
        }
    }

    afterEvaluate {
        val mergedJavadoc by registering(Javadoc::class) {
            setDestinationDir(layout.buildDirectory.dir("javadoc").get().asFile)
            val blackList = listOfNotNull(findProject(":ios"), project(":desktop"), project(":server"), project(":annotations"), findProject(":android"))
            source(rootProject.subprojects.map { p ->
                if (p in blackList || !p.hasProperty("sourceSets")) return@map null
                p.sourceSets.main.map { it.allJava }
            })
            classpath = files(rootProject.subprojects.map { p ->
                if (p in blackList || !p.hasProperty("sourceSets")) return@map null
                p.sourceSets.main.map { it.compileClasspath }
            })
        }
    }
}